lang:
  visualizerEnabled: "Your visualizer has been enabled."
  visualizerDisabled: "Your visualizer has been disabled."
  playersOnly: "Only a player can toggle his visualizer."
  selectionSizeOf: "The visualizer only works with selections up to a size of "
  blocks: " blocks"
  configReloaded: "Configuration for visualizer was reloaded from the disk."
particleDistance: 32
maxSize: 10000
checkForAxe: false
particleEffect: reddust
particleData: "255,255,255"
horizontalLinesForCuboid: true
horizontalLinesForPolygon: true
horizontalLinesForCylinder: true
horizontalLinesForEllipsoid: true
gapBetweenPoints: 0.5
verticalGap: 1
updateSelectionInterval: 20
updateParticlesInterval: 5
particleFadeDelay: 0
players: